MAIN := Main.py
LAUNCHING_SCENE := CombineScene

.PHONY: plq lq pmq mq phq hq

lq: 
	manim -ql $(MAIN) $(LAUNCH_SCENE)

mq:
	manim -qm $(MAIN) $(LAUNCH_SCENE)

hq:
	manim -qh $(MAIN) $(LAUNCH_SCENE)

plq: 
	manim -pql $(MAIN) $(LAUNCH_SCENE)

pmq:
	manim -pqm $(MAIN) $(LAUNCH_SCENE)

phq:
	manim -pqh $(MAIN) $(LAUNCH_SCENE)
